feat: Mailchimp
dittofeed/dittofeed pull request #1131
Opened 2024-11-06 10:56 UTC by neo773

/closes #1130 
/claims #1130

2024-11-06 18:51 UTC, maxgurewitz requested changes
Some requested changes, also there are some linter errors!

2024-11-06 20:20 UTC, neo773 commented on packages/backend-lib/src/messaging.ts
> +          website: "https://courier.com", // TODO: Add a default website or pass it from configuration
Yes, it's required by the library

2024-11-09 18:50 UTC, maxgurewitz commented on packages/backend-lib/src/messaging.ts
> +          website: "https://courier.com", // TODO: Add a default website or pass it from configuration
Can you change it to dittofeed.com then?

2024-11-09 18:53 UTC, neo773 commented on packages/backend-lib/src/messaging.ts
> +          website: "https://courier.com", // TODO: Add a default website or pass it from configuration
diff is outdated, we're deriving the website from sender email

2024-11-19 21:48 UTC, maxgurewitz approved these changes
Tested it out, webhooks working!

2024-11-19 21:48 UTC, merged