[DF-299] filter users by user property or segment value
dittofeed/dittofeed pull request #616
Opened 2024-01-31 01:27 UTC by oliverqx

/claim https://github.com/dittofeed/dittofeed/issues/579
Fixes https://github.com/dittofeed/dittofeed/issues/579

Will be done by EOD January 31st 2024

2024-02-01 23:46 UTC, maxgurewitz reviewed
Is this ready for review? If not can you make it a draft.

2024-02-02 02:09 UTC, oliverqx commented
@maxgurewitz not yet but it will be in a couple of hours

2024-02-14 22:06 UTC, maxgurewitz commented
@oliverqx when you're ready for review, add a video recording of the feature here!

2024-02-14 22:39 UTC, oliverqx commented
@maxgurewitz this is the video:

[Loom video showing the feature](https://www.loom.com/share/52d11a80d4d040a689454a50d8693caf?sid=895feed9-568d-4dd0-93fe-ea05a2e10f56)

2024-02-15 23:02 UTC, maxgurewitz requested changes
https://www.loom.com/share/265704bc91ef4df0a4bcde856081eb94?sid=7b08b1b5-69f1-4ff0-b89a-079bc82005b3

Hey! Some feedback described above:
1. Filter delete button is not working
2. Filtered values should use logical "AND" not logical "OR".
3. Find all property values as implemented in `findAllPropertyValues` is a performance no-go. There will be potentially millions of values (imagine the email user property), and loading them all via the API at once will cause things to blow up.

In the future, if we want to implement this feature, we can implement some kind of server side autocomplete, to look up a subset of matching values. However, that'll be a lot of work to implement.

My recommendation is to instead just allow workspace members to type arbitrary values into the text input without providing them info about the available values.

2024-02-15 23:04 UTC, maxgurewitz commented on packages/backend-lib/src/users.ts
> +    ? Prisma.sql`("segmentId" IN (${Prisma.join(segmentFilter.map((segmentId) => Prisma.sql`${segmentId}::uuid`))}))`
At some point we'll want to re-implement this method to query clickhouse instead of postgres, but that's not necessary for the time being.

2024-02-28 19:22 UTC, oliverqx commented
I recorded a video showing the changes:

https://www.loom.com/share/6ffcdb9bdb6d4371bb8163a0325367a5?sid=1fb43055-fbf0-468b-9ea2-7104e24982f8

2024-02-28 19:34 UTC, maxgurewitz commented
Sharing followup video so others can see: https://www.loom.com/share/6ffcdb9bdb6d4371bb8163a0325367a5?sid=1fb43055-fbf0-468b-9ea2-7104e24982f8

2024-03-01 03:05 UTC, maxgurewitz commented
@oliverqx the lint errors were related to the open-api schema check. if you merge main back in they should be fixed!

2024-03-02 00:57 UTC, maxgurewitz reviewed
Looks like you need to run, https://docs.dittofeed.com/contributing/updating-api-docs to update the api docs.

2024-03-02 02:29 UTC, oliverqx commented
thanks! was just debugging the issue you mentioned, will now update the api docs

2024-03-02 03:05 UTC, oliverqx commented
@maxgurewitz I think its ready

2024-03-02 17:14 UTC, maxgurewitz approved these changes

2024-03-02 17:15 UTC, merged