[DF-619] Added Related Resources Column
dittofeed/dittofeed pull request #628
Opened 2024-02-03 20:55 UTC by mehulmathur16

/claim #619
/fixes #619

2024-02-03 21:54 UTC, maxgurewitz requested changes
Can you post a recording showing a `BadWorkspaceConfiguration` event in the table specifically? You can trigger this by using a template that references a user property which is not defined on the user. Thank you!

2024-02-03 21:54 UTC, maxgurewitz commented on packages/dashboard/src/pages/events.page.tsx
> +  requestContext(async (_ctx, dfContext) => {
Can you also be sure to make these changes to the `/dashboard/users/[id]` page, which also displays events?

2024-02-03 21:54 UTC, maxgurewitz commented on packages/dashboard/src/components/eventsTable.tsx
> +      renderCell: ({ value }: GridRenderCellParams) => {
I realize that I should have been more explicit in the issue, but also need to relate segment and journey/broadcast resources as now described in the ticket.

2024-02-03 22:03 UTC, maxgurewitz requested changes
We also need to add the related resources to the sidebar.

2024-02-05 08:10 UTC, mehulmathur16 commented
> Can you post a recording showing a `BadWorkspaceConfiguration` event in the table specifically? You can trigger this by using a template that references a user property which is not defined on the user. Thank you!


https://github.com/dittofeed/dittofeed/assets/64700961/14f0a0f4-418b-49ec-b457-9a3eb7041ff1

2024-02-06 00:39 UTC, maxgurewitz approved these changes

2024-02-06 00:39 UTC, merged